### ISSUE TITLE
why use sleep?

### ISSUE THREAD

**Issue by zacksleo** [ikaras/yii2-oauth2-rest-docker#1]
in `/yii2-oauth2-rest-code/Dockerfile`, line 11 && 15, why use sleep?

**Comment by ikaras** [comment]
Waits while MySql container ups. This Dockerfile build only for demo, you need to build your own for prod/dev environments (i.e. no needs get code, dependencies each time when container starts)

**Comment by zacksleo** [comment]
thanks
